from mock import Mock

mock_issues = [
	# Single issues
	Mock(raw_data={
		u'labels': [],
		u'number': 248,
		u'assignee': {
			u'following_url': u'https://api.github.com/users/bencodev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/bencodev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/bencodev/orgs',
			u'url': u'https://api.github.com/users/bencodev',
			u'gists_url': u'https://api.github.com/users/bencodev/gists{/gist_id}',
			u'html_url': u'https://github.com/bencodev',
			u'subscriptions_url': u'https://api.github.com/users/bencodev/subscriptions',
			u'avatar_url': u'https://avatars3.githubusercontent.com/u/8027638?v=3',
			u'repos_url': u'https://api.github.com/users/bencodev/repos',
			u'received_events_url': u'https://api.github.com/users/bencodev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/bencodev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'bencodev',
			u'type': u'User',
			u'id': 8027638,
			u'followers_url': u'https://api.github.com/users/bencodev/followers'
		},
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 216846343,
		u'title': u'Issue Super Title',
		u'comments': 0,
		u'state': u'open',
		u'body': u'',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/248/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/248/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/248/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/248',
		u'updated_at': u'2017-03-24T16:57:52Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/bencodev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/bencodev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/bencodev/orgs',
			u'url': u'https://api.github.com/users/bencodev',
			u'gists_url': u'https://api.github.com/users/bencodev/gists{/gist_id}',
			u'html_url': u'https://github.com/bencodev',
			u'subscriptions_url': u'https://api.github.com/users/bencodev/subscriptions',
			u'avatar_url': u'https://avatars3.githubusercontent.com/u/8027638?v=3',
			u'repos_url': u'https://api.github.com/users/bencodev/repos',
			u'received_events_url': u'https://api.github.com/users/bencodev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/bencodev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'bencodev',
			u'type': u'User',
			u'id': 8027638,
			u'followers_url': u'https://api.github.com/users/bencodev/followers'
		},
		u'milestone': None,
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/248',
		u'created_at': u'2017-03-24T16:57:52Z',
		u'assignees': [{
			               u'following_url': u'https://api.github.com/users/bencodev/following{/other_user}',
			               u'events_url': u'https://api.github.com/users/bencodev/events{/privacy}',
			               u'organizations_url': u'https://api.github.com/users/bencodev/orgs',
			               u'url': u'https://api.github.com/users/bencodev',
			               u'gists_url': u'https://api.github.com/users/bencodev/gists{/gist_id}',
			               u'html_url': u'https://github.com/bencodev',
			               u'subscriptions_url': u'https://api.github.com/users/bencodev/subscriptions',
			               u'avatar_url': u'https://avatars3.githubusercontent.com/u/8027638?v=3',
			               u'repos_url': u'https://api.github.com/users/bencodev/repos',
			               u'received_events_url': u'https://api.github.com/users/bencodev/received_events',
			               u'gravatar_id': u'',
			               u'starred_url': u'https://api.github.com/users/bencodev/starred{/owner}{/repo}',
			               u'site_admin': False,
			               u'login': u'bencodev',
			               u'type': u'User',
			               u'id': 8027638,
			               u'followers_url': u'https://api.github.com/users/bencodev/followers'
		               }]
	}),
	Mock(raw_data={
		u'labels': [],
		u'number': 247,
		u'assignee': {
			u'following_url': u'https://api.github.com/users/bencodev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/bencodev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/bencodev/orgs',
			u'url': u'https://api.github.com/users/bencodev',
			u'gists_url': u'https://api.github.com/users/bencodev/gists{/gist_id}',
			u'html_url': u'https://github.com/bencodev',
			u'subscriptions_url': u'https://api.github.com/users/bencodev/subscriptions',
			u'avatar_url': u'https://avatars3.githubusercontent.com/u/8027638?v=3',
			u'repos_url': u'https://api.github.com/users/bencodev/repos',
			u'received_events_url': u'https://api.github.com/users/bencodev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/bencodev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'bencodev',
			u'type': u'User',
			u'id': 8027638,
			u'followers_url': u'https://api.github.com/users/bencodev/followers'
		},
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 216811377,
		u'title': u'Issue Super Title 2',
		u'comments': 0,
		u'state': u'open',
		u'body': u'',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/247/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/247/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/247/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/247',
		u'updated_at': u'2017-03-24T14:59:10Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/bencodev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/bencodev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/bencodev/orgs',
			u'url': u'https://api.github.com/users/bencodev',
			u'gists_url': u'https://api.github.com/users/bencodev/gists{/gist_id}',
			u'html_url': u'https://github.com/bencodev',
			u'subscriptions_url': u'https://api.github.com/users/bencodev/subscriptions',
			u'avatar_url': u'https://avatars3.githubusercontent.com/u/8027638?v=3',
			u'repos_url': u'https://api.github.com/users/bencodev/repos',
			u'received_events_url': u'https://api.github.com/users/bencodev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/bencodev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'bencodev',
			u'type': u'User',
			u'id': 8027638,
			u'followers_url': u'https://api.github.com/users/bencodev/followers'
		},
		u'milestone': None,
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/247',
		u'created_at': u'2017-03-24T14:59:10Z',
		u'assignees': [{
			               u'following_url': u'https://api.github.com/users/bencodev/following{/other_user}',
			               u'events_url': u'https://api.github.com/users/bencodev/events{/privacy}',
			               u'organizations_url': u'https://api.github.com/users/bencodev/orgs',
			               u'url': u'https://api.github.com/users/bencodev',
			               u'gists_url': u'https://api.github.com/users/bencodev/gists{/gist_id}',
			               u'html_url': u'https://github.com/bencodev',
			               u'subscriptions_url': u'https://api.github.com/users/bencodev/subscriptions',
			               u'avatar_url': u'https://avatars3.githubusercontent.com/u/8027638?v=3',
			               u'repos_url': u'https://api.github.com/users/bencodev/repos',
			               u'received_events_url': u'https://api.github.com/users/bencodev/received_events',
			               u'gravatar_id': u'',
			               u'starred_url': u'https://api.github.com/users/bencodev/starred{/owner}{/repo}',
			               u'site_admin': False,
			               u'login': u'bencodev',
			               u'type': u'User',
			               u'id': 8027638,
			               u'followers_url': u'https://api.github.com/users/bencodev/followers'
		               }]
	}),
	Mock(raw_data={
		u'labels': [{
			            u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/labels/task',
			            u'color': u'fbca04',
			            u'default': False,
			            u'id': 500865110,
			            u'name': u'task'
		            }],
		u'number': 246,
		u'assignee': None,
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 216715567,
		u'title': u'Issue Super Title 3',
		u'comments': 0,
		u'state': u'open',
		u'body': u'https://trello.com/c/6AJrD7S1/152-fermeture-sur-partoo-modif\r\n\r\nReport to Steeve',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/246/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/246/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/246/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/246',
		u'updated_at': u'2017-03-24T09:30:16Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'milestone': None,
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/246',
		u'created_at': u'2017-03-24T09:30:16Z',
		u'assignees': []
	}),

	# Associated issues
	## Issue associated to a milestone
	Mock(raw_data={
		u'labels': [],
		u'number': 234,
		u'assignee': None,
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 215997709,
		u'title': u'Issue Super Title 4',
		u'comments': 0,
		u'state': u'open',
		u'body': u'We are paying by nb of businesses which are activated.\r\nWe should find a way to mark the business as unactivated on Foursquare.',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/234/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/234/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/234/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/234',
		u'updated_at': u'2017-03-22T09:19:54Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'milestone': {
			u'description': u'',
			u'title': u'Milestone Super Title',
			u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/14',
			u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/14/labels',
			u'created_at': u'2017-01-17T20:23:24Z',
			u'creator': {
				u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
				u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
				u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
				u'url': u'https://api.github.com/users/BenCoDev',
				u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
				u'html_url': u'https://github.com/BenCoDev',
				u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
				u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
				u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
				u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
				u'gravatar_id': u'',
				u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
				u'site_admin': False,
				u'login': u'BenCoDev',
				u'type': u'User',
				u'id': 4339031,
				u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
			},
			u'number': 14,
			u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/milestone/14',
			u'updated_at': u'2017-03-22T09:19:54Z',
			u'due_on': u'2017-02-17T08:00:00Z',
			u'state': u'open',
			u'closed_issues': 5,
			u'open_issues': 1,
			u'closed_at': None,
			u'id': 2259593
		},
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/234',
		u'created_at': u'2017-03-22T09:19:54Z',
		u'assignees': []
	}),

	## Issue associated to another milestone
	Mock(raw_data={
		u'labels': [{
			            u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/labels/task',
			            u'color': u'fbca04',
			            u'default': False,
			            u'id': 500865110,
			            u'name': u'task'
		            }],
		u'number': 217,
		u'assignee': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 214811722,
		u'title': u'Issue Super Title 5',
		u'comments': 2,
		u'state': u'open',
		u'body': u'',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/217/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/217/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/217/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/217',
		u'updated_at': u'2017-03-23T19:05:57Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'milestone': {
			u'description': u'Enable users to do bulk matching on the web app',
			u'title': u'Milestone Super Title 2',
			u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/5',
			u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/5/labels',
			u'created_at': u'2017-01-02T11:53:05Z',
			u'creator': {
				u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
				u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
				u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
				u'url': u'https://api.github.com/users/BenCoDev',
				u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
				u'html_url': u'https://github.com/BenCoDev',
				u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
				u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
				u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
				u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
				u'gravatar_id': u'',
				u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
				u'site_admin': False,
				u'login': u'BenCoDev',
				u'type': u'User',
				u'id': 4339031,
				u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
			},
			u'number': 5,
			u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/milestone/5',
			u'updated_at': u'2017-03-24T16:57:14Z',
			u'due_on': u'2017-03-31T07:00:00Z',
			u'state': u'open',
			u'closed_issues': 4,
			u'open_issues': 7,
			u'closed_at': None,
			u'id': 2223205
		},
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/217',
		u'created_at': u'2017-03-16T19:20:56Z',
		u'assignees': [{
			               u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			               u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			               u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			               u'url': u'https://api.github.com/users/BenCoDev',
			               u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			               u'html_url': u'https://github.com/BenCoDev',
			               u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			               u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			               u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			               u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			               u'gravatar_id': u'',
			               u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			               u'site_admin': False,
			               u'login': u'BenCoDev',
			               u'type': u'User',
			               u'id': 4339031,
			               u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		               }]
	}),
	Mock(raw_data={
		u'labels': [{
			            u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/labels/task',
			            u'color': u'fbca04',
			            u'default': False,
			            u'id': 500865110,
			            u'name': u'task'
		            }],
		u'number': 191,
		u'assignee': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 211369970,
		u'title': u'Issue Super Title 6',
		u'comments': 0,
		u'state': u'open',
		u'body': u'- [x] (remove mako logic)\r\n- [x]  components structure (static)\r\n- [x] implement structure\r\n- [x] add interactions\r\n    - [ ] fetch data from google account\r\n- [x] style page\r\n- [ ] Dsiplay number of matched v. unMatched in Partner Connections Box (outside bulk matching app)\r\n    * make sure to keep in mind new businesses selected but not yet created by pusher. e.g. `partners.google_my_business.account_name` but no `partners.google_my_business.id`',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/191/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/191/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/191/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/191',
		u'updated_at': u'2017-03-21T09:58:34Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'milestone': {
			u'description': u'Enable users to do bulk matching on the web app',
			u'title': u'Milestone Super Title 2',
			u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/5',
			u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/5/labels',
			u'created_at': u'2017-01-02T11:53:05Z',
			u'creator': {
				u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
				u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
				u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
				u'url': u'https://api.github.com/users/BenCoDev',
				u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
				u'html_url': u'https://github.com/BenCoDev',
				u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
				u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
				u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
				u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
				u'gravatar_id': u'',
				u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
				u'site_admin': False,
				u'login': u'BenCoDev',
				u'type': u'User',
				u'id': 4339031,
				u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
			},
			u'number': 5,
			u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/milestone/5',
			u'updated_at': u'2017-03-24T16:57:14Z',
			u'due_on': u'2017-03-31T07:00:00Z',
			u'state': u'open',
			u'closed_issues': 4,
			u'open_issues': 7,
			u'closed_at': None,
			u'id': 2223205
		},
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/191',
		u'created_at': u'2017-03-02T11:55:31Z',
		u'assignees': [{
			               u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			               u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			               u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			               u'url': u'https://api.github.com/users/BenCoDev',
			               u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			               u'html_url': u'https://github.com/BenCoDev',
			               u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			               u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			               u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			               u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			               u'gravatar_id': u'',
			               u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			               u'site_admin': False,
			               u'login': u'BenCoDev',
			               u'type': u'User',
			               u'id': 4339031,
			               u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		               }]
	}),

	## Issue associated to another milestone
	Mock(raw_data={
		u'labels': [{
			            u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/labels/enhancement',
			            u'color': u'84b6eb',
			            u'default': True,
			            u'id': 496423043,
			            u'name': u'enhancement'
		            }],
		u'number': 199,
		u'assignee': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'repository_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo',
		u'closed_at': None,
		u'id': 213373476,
		u'title': u'Issue Super Title 7',
		u'comments': 0,
		u'state': u'open',
		u'body': u'Reduc Avenue only works for promos\r\n\r\nWe should check if promos is filled for the business\r\nIf not, we should have a config_required status\r\nOn the detail view there should be some explanations and a redirection to edit\r\n',
		u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/199/labels{/name}',
		u'events_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/199/events',
		u'comments_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/199/comments',
		u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/issues/199',
		u'updated_at': u'2017-03-15T17:07:00Z',
		u'user': {
			u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			u'url': u'https://api.github.com/users/BenCoDev',
			u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			u'html_url': u'https://github.com/BenCoDev',
			u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			u'gravatar_id': u'',
			u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			u'site_admin': False,
			u'login': u'BenCoDev',
			u'type': u'User',
			u'id': 4339031,
			u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		},
		u'milestone': {
			u'description': u'New version of PM with ability to see aggregated PM by org',
			u'title': u'Milestone Super Title 3',
			u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/1',
			u'labels_url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/milestones/1/labels',
			u'created_at': u'2016-12-07T20:12:31Z',
			u'creator': {
				u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
				u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
				u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
				u'url': u'https://api.github.com/users/BenCoDev',
				u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
				u'html_url': u'https://github.com/BenCoDev',
				u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
				u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
				u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
				u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
				u'gravatar_id': u'',
				u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
				u'site_admin': False,
				u'login': u'BenCoDev',
				u'type': u'User',
				u'id': 4339031,
				u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
			},
			u'number': 1,
			u'html_url': u'https://github.com/MySuperOrg/MySuperRepo/milestone/1',
			u'updated_at': u'2017-03-16T17:44:59Z',
			u'due_on': u'2016-12-16T08:00:00Z',
			u'state': u'open',
			u'closed_issues': 25,
			u'open_issues': 10,
			u'closed_at': None,
			u'id': 2182613
		},
		u'closed_by': None,
		u'locked': False,
		u'url': u'https://api.github.com/repos/MySuperOrg/MySuperRepo/issues/199',
		u'created_at': u'2017-03-10T15:38:22Z',
		u'assignees': [{
			               u'following_url': u'https://api.github.com/users/BenCoDev/following{/other_user}',
			               u'events_url': u'https://api.github.com/users/BenCoDev/events{/privacy}',
			               u'organizations_url': u'https://api.github.com/users/BenCoDev/orgs',
			               u'url': u'https://api.github.com/users/BenCoDev',
			               u'gists_url': u'https://api.github.com/users/BenCoDev/gists{/gist_id}',
			               u'html_url': u'https://github.com/BenCoDev',
			               u'subscriptions_url': u'https://api.github.com/users/BenCoDev/subscriptions',
			               u'avatar_url': u'https://avatars1.githubusercontent.com/u/4339031?v=3',
			               u'repos_url': u'https://api.github.com/users/BenCoDev/repos',
			               u'received_events_url': u'https://api.github.com/users/BenCoDev/received_events',
			               u'gravatar_id': u'',
			               u'starred_url': u'https://api.github.com/users/BenCoDev/starred{/owner}{/repo}',
			               u'site_admin': False,
			               u'login': u'BenCoDev',
			               u'type': u'User',
			               u'id': 4339031,
			               u'followers_url': u'https://api.github.com/users/BenCoDev/followers'
		               }]
	}),
]


class IssueGenerator:
	totalCount = len(mock_issues)

	def __iter__(self):
		for issue in mock_issues:
			yield issue


mock_get_repo = Mock(
	return_value=Mock(
		get_issues=Mock(
			return_value=IssueGenerator()
		)
	)
)
